groups:
recipes:
    global:
        - dotfiles::bash_it
        - dotfiles::inputrc
    mac_os_x:
        - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        - osxdefaults::set_computer_name
attributes:
    git:
        name: Will Lovett
        email: willlovett@gmail.com
    osxdefaults:
        computername: iago
    homebrewalt:
        cask_apps:
            - coconutbattery
            - gimp
            - moom
            - omnifocus
            - omnigraffle
            - rftg
            - spotify
            - xbmc
