groups:
recipes:
    global:
        - dotfiles::bash_it
        - dotfiles::inputrc
    mac_os_x:
        - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        - osxdefaults::set_computer_name
        - custom-applications::xdot
attributes:
    git:
        name: Will Lovett
        email: willlovett@gmail.com
        aliases:
            co: checkout
            ci: commit
            st: status
            gr: log --graph --full-history --all --color --pretty=tformat:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s%x20%x1b[33m(%an)%x1b[0m"
    osxdefaults:
        computername: e105278-mac
    homebrewalt:
        cask_apps:
            - coconutbattery
            - gimp
            - moom
            - omnifocus
            - omnigraffle
            - rftg
            - spotify
            - xbmc
            - xmarks-safari
    bash_it:
        enabled_plugins:
            aliases:
                - emacs
