recipes:                                       # Configs are parsed and every list is appended to each other, chef handles order and de-duplication
    global:                                    # Recipes mentioned under "global" are installed for all operating systems (we used to support linux, and may do so in the future)
        - applications::create_var_chef_cache
    mac_os_x:                                  # Recipes mentioned under "mac_os_x" are installed on OSX and OSX Server
        - dotfiles::gitconfig
        - dotfiles::vim
        - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::add_note_to_loginscreen
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::disable_auto-correct
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::disable_resume_system-wide
        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::save_screenshots_to_the_desktop
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::set_terminal_profile
attributes:
    osxdefaults:
        loginmessage: Property of Will Lovett.  (UK) 07590602367.  willlovett@gmail.com
    homebrewalt:
        apps:
            - bash
            - bash-completion
            - git
            - git-flow
            - gnu-tar
            - gnu-which
            - htop-osx
            - pv
            - pwgen
            - watch
            - wget
            - xchat
        cask_apps:
            - adium
            - adobe-reader
            - chefdk
            - dropbox
            - emacs
            - firefox
            - google-chrome
            - iterm2
            - java
            - limechat
            - skype
            - sourcetree
            - sublime-text3
            - unrarx
            - virtualbox
            - vlc
