recipes:
    global:
        - applications::git
        - applications::wget
        - applications::pwgen
        - applications::xmlstarlet
        - applications::pv
        - applications::htop
        - dotfiles::gitconfig
        - applications::git-flow
        - applications::ssh_config
        - dotfiles::vim
        - applications::xchat
    mac_os_x:
        - applications::gnu-which
        - applications::sublime_text_3
        - applications::watch
        - applications::gnu-tar
        - applications::sourcetree
        - applications::adium
        - applications::dropbox
        - applications::emacs
        - applications::firefox
        - applications::virtualbox
        - applications::libreoffice
        - applications::skype
        - applications::unrarx
        - applications::limechat
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
    debian:
        - applications::performance_scheduler
        - applications::nscd
        - applications::locales
        - applications::pureftpd
        - applications::xvfb
        - applications::pidgin
        - applications::ubuntu-desktop
